apiVersion: apps/v1
kind: Deployment
metadata:
  name: ascii-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ascii-art
  template:
    metadata:
      labels:
        app: ascii-art
    spec:
      containers:
        - name: ascii-art1
          image: adalbertbarta/go:v1.0.0
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: ascii-service
spec:
  selector:
    app: ascii-art
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080

#minikube start
#minikube status
#kubectl get po,svc,deployments
#kubectl apply -f deploy_ascii_art.yaml 
#kubectl port-forward deployments/ascii-deployment 8000:8080
#kind --help
#k3d --help
#kind create cluster --name ascidemo
#kubectl cluster-info --context kind-ascidemo
#kubectl describe deploy/ascii-deployment
#k3d cluster create demoascii
#kubectl cluster-info
#kubectl cluster-info dump

#Please install asciinema
#https://asciinema.org/docs/installation