apiVersion: v1
kind: Secret
metadata:
  name: mysecret
data:
  MY_SECRET_ENV_VAR: c3RlYWs=
---
apiVersion: v1
kind: Pod
metadata:
  name: mypod
spec:
  containers:
  - name: mycontainer
    image: nginx
    env:
    - name: MY_SECRET_ENV_VAR
      valueFrom:
        secretKeyRef:
          name: mysecret
          key: MY_SECRET_ENV_VAR